services:
  - type: web
    name: iiit-kalyani-voting-system
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: PORT
        value: "8080"
    healthCheckPath: /B7iii_VotingApp_MavenProject_Final/
    autoDeploy: true
